### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by martinkarugaba** [martinkarugaba/my-catalog#35]
# Set up kanban board

- [ ] [Here is the link to our project](https://github.com/martinkarugaba/my-catalog/projects/1)
- [ ] We are three people on our team
- [ ] @martinkarugaba - `Team member #1`
- [ ] @newtonah0 - `Team member #2`
- [ ] @enocol - `Team meber #3`

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @martinkarugaba, @newtonah0 and @enocol,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] There is no issue for this task. Kindly add it or edit [this issue's](https://github.com/martinkarugaba/my-catalog/issues/7) description and add it there

  ![image](https://github.com/martinkarugaba/my-catalog/assets/36542986/8f08bc83-47f6-4e18-b244-928631b28e30)

- [ ] You have a lot of tasks with no descriptions. Kindly add the descriptions now.

  ![image](https://github.com/martinkarugaba/my-catalog/assets/36542986/30e960e4-a611-49ec-8560-bf02669888f3)
  ![image](https://github.com/martinkarugaba/my-catalog/assets/36542986/1aeac61f-36d3-422c-b7e1-f5a688d08702)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by martinkarugaba** [comment]
# :recycle: Changes made

- [ ] Added missing issue
- [ ] Added all missing descriptions

**Comment by danmainah** [comment]
Hi @martinkarugaba , @newtonah0 and @enocol , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️  Implement the change requested to add missing tasks and ensure all cards have description.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
